### ISSUE TITLE
Compatibility with Python 3.10

### ISSUE THREAD

**Issue by tkhamez** [bravecollective/structurebot#1]
Currently there's at least one error from pyswagger: `AttributeError: module 'collections' has no attribute 'MutableMapping'`.

**Comment by tkhamez** [comment]
https://github.com/pyopenapi/pyswagger/issues/196

**Comment by tkhamez** [comment]
https://github.com/Kyria/EsiPy/issues/64

**Comment by PabloCastellano** [comment]
Fix available here https://github.com/fboerman/pyswagger/commit/52019f41678d3f91f7f8dfc06387e0afd328ae38

**Comment by tkhamez** [comment]
I want to replace pyswagger completely and simply use requests.

**Comment by rmacy** [comment]
+1 to requests

**Comment by tkhamez** [comment]
It's more or less done, but was not finished.

Current problems:

- There are new TODOs in the source code, like "add page-handling".
- The variable `resp_data` in `esi_get()` does not exist.
- Test only run successfully if each file is executed individually. Probably a caching problem, maybe in the function `name_to_id()`.

**Comment by tkhamez** [comment]
Fixed variable.

The rest is acceptable for the moment.
